#!/bin/bash
# My Post Install Script (Fedora Silverblue)

flatpak install flathub com.spotify.Client -y
flatpak install flathub org.gimp.GIMP -y
flatpak install flathub org.inkscape.Inkscape -y
flatpak install flathub com.visualstudio.code -y
flatpak install flathub org.kde.kdenlive -y
flatpak install flathub org.telegram.desktop -y
flatpak install flathub com.discordapp.Discord -y
flatpak install flathub org.shotcut.Shotcut -y
flatpak install flathub org.kde.krita -y
flatpak install flathub com.adobe.Flash-Player-Projector -y
flatpak install flathub org.audacityteam.Audacity -y
flatpak install flathub io.github.celluloid_player.Celluloid -y
flatpak install flathub org.gnome.Cheese -y
flatpak install flathub fr.handbrake.ghb -y
flatpak install flathub org.mixxx.Mixxx -y
flatpak install flathub com.obsproject.Studio -y
flatpak install flathub org.olivevideoeditor.Olive -y
flatpak install flathub org.openshot.OpenShot -y
flatpak install flathub org.gnome.SoundRecorder -y
flatpak install flathub org.videolan.VLC -y
flatpak install flathub cc.arduino.arduinoide -y
flatpak install flathub com.visualstudio.code.oss -y
flatpak install flathub org.blender.Blender -y
flatpak install flathub net.scribus.Scribus -y
flatpak install flathub org.gnome.Shotwell -y
flatpak install flathub org.filezillaproject.Filezilla -y
flatpak install flathub info.mumble.Mumble -y
flatpak install flathub org.remmina.Remmina -y
flatpak install flathub me.kozec.syncthingtk -y
flatpak install flathub com.transmissionbt.Transmission -y
flatpak install flathub com.github.unrud.VideoDownloader -y
flatpak install flathub org.wireshark.Wireshark -y
flatpak install flathub org.gabmus.whatip -y
flatpak install flathub us.zoom.Zoom -y
flatpak install flathub io.github.wereturtle.ghostwriter -y
flatpak install flathub com.bitwarden.desktop -y
flatpak install flathub com.gitlab.davem.ClamTk -y
flatpak install flathub com.github.miguelmota.Cointop -y
flatpak install flathub org.gnome.Boxes -y
flatpak install flathub org.flameshot.Flameshot -y
flatpak install flathub im.pidgin.Pidgin -y
flatpak install flathub net.runelite.RuneLite -y
flatpak install flathub md.obsidian.Obsidian -y
flatpak install flathub org.onlyoffice.desktopeditors -y
flatpak install flathub ca.hamaluik.Timecop -y
flatpak install flathub org.gnome.gitlab.YaLTeR.VideoTrimmer -y
flatpak install flathub org.gnome.World.PikaBackup -y
flatpak install flathub com.rafaelmardojai.Blanket -y
flatpak install flathub net.cozic.joplin_desktop -y
flatpak install flathub com.microsoft.Edge -y
flatpak install flathub com.github.tchx84.Flatseal -y
flatpak install flathub com.wps.Office -y
flatpak install flathub com.github.wwmm.easyeffects -y
flatpak install flathub org.godotengine.Godot -y
flatpak install flathub im.riot.Riot -y
flatpak install flathub io.github.giantpinkrobots.flatsweep -y
flatpak install flathub org.raspberrypi.rpi-imager -y
flatpak install flathub com.raggesilver.BlackBox -y
flatpak install flathub com.leinardi.gwe -y
flatpak install flathub io.github.prateekmedia.appimagepool -y
flatpak install flathub org.gnome.DejaDup -y

